-- Table for ABC/Canntaireachd/BMW token recognition and conversion
CREATE TABLE IF NOT EXISTS abc_dict_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    abc_token VARCHAR(255) NOT NULL,
    cannt_token VARCHAR(255),
    bmw_token VARCHAR(255),
    description TEXT
);
-- Example data
INSERT IGNORE INTO abc_dict_tokens (abc_token, cannt_token, bmw_token, description) VALUES
    ('G', 'em', NULL, 'Low G'),
    ('A', 'en', NULL, 'Low A'),
    ('B', 'o', NULL, 'B'),
    ('c', 'o', NULL, 'C'),
    ('d', 'a', NULL, 'D'),
    ('e', 'e', NULL, 'E'),
    ('f', 've', NULL, 'F'),
    ('g', 'di', NULL, 'High G'),
    ('a', 'I', NULL, 'High A'),
    ('{g}G', 'hem', NULL, 'G gracenote on G'),
    ('{g}A', 'hen', NULL, 'G gracenote on A'),
    ('{g}B', 'ho', NULL, 'G gracenote on B'),
    ('{g}c', 'ho', NULL, 'G gracenote on C'),
    ('{g}d', 'ha', NULL, 'G gracenote on D'),
    ('{g}e', 'he', NULL, 'G gracenote on E'),
    ('{g}f', 'che', NULL, 'G gracenote on F'),
    ('{d}G', 'dam', NULL, 'D gracenote on G'),
    ('{d}A', 'dan', NULL, 'D gracenote on A'),
    ('{d}B', 'to', NULL, 'D gracenote on B'),
    ('{d}c', 'do', NULL, 'D gracenote on C'),
    ('{e}G', 'um', NULL, 'E gracenote on G'),
    ('{e}A', 'un', NULL, 'E gracenote on A'),
    ('{e}B', 'eo', NULL, 'E gracenote on B'),
    ('{e}c', 'eo', NULL, 'E gracenote on C'),
    ('{e}d', 'ea', NULL, 'E gracenote on D'),
    ('{a}G', 'him', NULL, 'A gracenote on G'),
    ('{a}A', 'hin', NULL, 'A gracenote on A'),
    ('{a}B', 'ho', NULL, 'A gracenote on B'),
    ('{a}c', 'ho', NULL, 'A gracenote on C'),
    ('{a}d', 'ha', NULL, 'A gracenote on D'),
    ('{a}e', 'he', NULL, 'A gracenote on E'),
    ('{a}f', 'che', NULL, 'A gracenote on F'),
    ('{a}g', 'chi', NULL, 'A gracenote on G'),
    ('{G}A', 'ren', NULL, 'Strike on A'),
    ('{AG}A', 'ren', NULL, 'Strike on A'),
    ('{G}B', 'ro', NULL, 'Strike on B'),
    ('{BG}B', 'ro', NULL, 'Strike on B'),
    ('{G}c', 'ro', NULL, 'Strike on C'),
    ('{cG}c', 'ro', NULL, 'Strike on C'),
    ('{G}d', 'ra', NULL, 'Strike on D'),
    ('{dG}d', 'ra', NULL, 'Strike on D'),
    ('{c}d', 'ola', NULL, 'Strike on D'),
    ('{dc}d', 'ala', NULL, 'Strike on '),
    ('{A}e', 're', NULL, 'Strike on '),
    ('{eA}e', 're', NULL, 'Strike on '),
    ('{e}f', 'eve', NULL, 'Strik on e'),
    ('{fe}f', 'eve', NULL, 'Strike on '),
    ('{f}g', 'vedi', NULL, 'Strike on '),
    ('{gf}g', 'chedi', NULL, 'Strike on '),
    ('{g}a', 'li', NULL, 'Strike on '),
    ('{ag}a', 'dili', NULL, 'Strike on '),
    ('{GAG}A', 'rarin', NULL, 'Birl'),
    ('{AGAG}A', 'enrarin', NULL, 'Birl'),
    ('{gAGAG}A', 'henrarin', NULL, 'Birl'),
    ('{aAGAG}A', 'hinrarin', NULL, 'Birl'),
    ('{GBG}A', 'roro', NULL, 'Double Echo'),
    ('{GcG}c', 'roro', NULL, 'Double Echo'),
    ('{GdG}d', 'rara', NULL, 'Double Echo'),
    ('{cdc}d', 'rara', NULL, 'Double Echo'),
    ('{AeA}e', 'rede', NULL, 'Double Echo'),
    ('{efe}f', 'rere', NULL, 'Double Echo'),
    ('{fgf}g', 'riri', NULL, 'Double Echo'),
    ('{gag}a', 'riri', NULL, 'Double Echo'),
    ('{BGBG}', 'hodo', NULL, 'Double Echo'),
    ('{gBGBG}B', 'horodo', NULL, 'Double Echo'),
    ('{gBGBG}', 'horodo', NULL, 'Double Echo'),
    ('{aBGBG}B', 'horodo', NULL, 'Double Echo'),
    ('{aBGBG}', 'horodo', NULL, 'Double Echo'),
    ('{cGcG}', 'rodo', NULL, 'Double Echo'),
    ('gcGcG}c', 'horodo', NULL, 'Double Echo'),
    ('gcGcG}', 'horodo', NULL, 'Double Echo');
